### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nicholsn** [OpenNeuroLab/metasearch#1]
- [x]  Download all project files from fcp-indi bucket on S3
- [x] Create mapping approach
- [x] Create docs/process for how to contribute
- [x] Merge phenotypic data into a single csv
- [ ] Create Data Dictionaries

**Comment by satra** [comment]
- [x] create species column
